### ISSUE TITLE
Importing the multiarray numpy extension module failed

### ISSUE THREAD

**Issue by hernangarcia** [aws-samples/amazon-macie-activity-generator#1]
Hello!

After deploying the CFN template I see this error in the lambda function:

nable to import module 'main': 
Importing the multiarray numpy extension module failed. Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control). Otherwise reinstall numpy.

Original error was: cannot import name multiarray

-------

Is it related to python expecting UCS4 unicode? Can you help me with the fix?

Thanks a lot in advance.

**Comment by nimasharifimehr** [comment]
Hi @hernangarcia, Thank you for reporting the issue. I will be updating the deploy script to 1) avoid using any cached version of dependencies and 2) fail the deployment if any initial step in the script has failed. This could help to identify which steps are failing.

Also please note that this package has been tested with python 2.7 and needs to be built and deployed from a host running Amazon Linux to ensure native binaries (i.e. numpy) are build compatibile for running in AWS Lambda functions.

**Comment by nimasharifimehr** [comment]
Changes are pushed into Master: https://github.com/aws-samples/amazon-macie-activity-generator/commit/e09325e35e52aa526837d1112096a44ba74a37a5

@hernangarcia, can you please try deploying the latest code from a host running Amazon Linux and let me know the outcome.

**Comment by nimasharifimehr** [comment]
@hernangarcia, a couple more items for you to build and deploy the package successfully (I will also add these to README doc):

1) Preparing host to Compile Software using: sudo yum groupinstall "Development Tools"
2) Upgrade your pip using: sudo pip install --upgrade pip
3) Fix path to pip after upgrade: hash -r

**Comment by hernangarcia** [comment]
Awesome @nimasharifimehr ! Works like a charm 👍 

Thanks for the quick reply and updates.

One thing that may be helpful to add to the README doc: the ec2 instance must have access to the specified S3 bucket when running the deploy command :)

Thanks a lot!

**Comment by nimasharifimehr** [comment]
Thank you @hernangarcia. I updated the README doc and in the next iteration I will also publish a template policy with the least privileges required to run the deploy script.
